# Generated by Django 6.0.3 on 2026-04-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_message_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='job',
            name='longitude',
        ),
    ]
