# Generated by Django 6.0.3 on 2026-04-01 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_job_latitude_remove_job_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.AddField(
            model_name='requirement',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='jobs.job'),
        ),
    ]
