# Generated by Django 6.0.4 on 2026-04-14 11:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_benefit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='target_user',
        ),
        migrations.AddField(
            model_name='company',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dxek6c0tg/image/upload/v1776164942/OIP_1_pq3xtt.webp', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dxek6c0tg/image/upload/v1776164791/OIP_lqphcr.webp', max_length=255),
        ),
    ]
