# Generated by Django 6.0.4 on 2026-04-14 11:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_review_target_user_company_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1776164942/OIP_1_pq3xtt.webp', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1776164791/OIP_lqphcr.webp', max_length=255),
        ),
    ]
